version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  file_handler:
    class: logging.FileHandler
    formatter: standard
    filename: uvicorn.log
loggers:
  uvicorn:
    handlers: [file_handler]
    level: INFO
  uvicorn.error:
    handlers: [file_handler]
    level: INFO
  uvicorn.access:
    handlers: [file_handler]
    level: INFO